[package]
name = "TinyAudioExample"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]
name = "tinyaudioexample"

[dependencies]
tinyaudio = { path = "../../" }
wasm-bindgen = "0.2.92"
